# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Troj_diffusion_seminar',
                'doc_host': 'https://akansh12.github.io',
                'git_url': 'https://github.com/akansh12/Troj_diffusion_seminar',
                'lib_path': 'Troj_diffusion_seminar'},
  'syms': {'Troj_diffusion_seminar.core': {'Troj_diffusion_seminar.core.foo': ('core.html#foo', 'Troj_diffusion_seminar/core.py')}}}
