name: heat
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - ca-certificates=2024.2.2
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - ipykernel=6.29.1
  - ipython=8.18.1
  - ipywidgets=8.1.2
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.7.1
  - jupyterlab_widgets=3.0.10
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=23.3
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.1
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.14.1
  - typing_extensions=4.9.0
  - tzdata=2023c
  - wcwidth=0.2.13
  - wheel=0.41.2
  - widgetsnbextension=4.0.10
  - xz=5.4.2
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - blobfile==2.0.1
      - certifi==2022.12.7
      - charset-normalizer==3.0.1
      - clean-fid==0.1.35
      - click==8.1.7
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - filelock==3.9.0
      - fonttools==4.47.2
      - gitdb==4.0.11
      - gitpython==3.1.41
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.51.1
      - idna==3.4
      - importlib-resources==6.1.1
      - kiwisolver==1.4.5
      - lmdb==1.4.0
      - lxml==4.9.2
      - markdown==3.4.1
      - matplotlib==3.8.2
      - ml-collections==0.1.1
      - mpi4py==3.1.5
      - numpy==1.24.2
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - omegaconf==2.3.0
      - opencv-python==4.7.0.68
      - pillow==9.4.0
      - protobuf==3.20.3
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycryptodomex==3.17
      - pyparsing==3.1.1
      - pyyaml==6.0
      - requests==2.28.2
      - scipy==1.10.0
      - sentry-sdk==1.40.3
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - torch==1.13.1
      - torchvision==0.14.1
      - tqdm==4.64.1
      - typing-extensions==4.4.0
      - urllib3==1.26.14
      - wandb==0.16.3
      - werkzeug==2.2.2
      - zipp==3.17.0
